homeTitle = "Rouke's Blog"
subtitle = "Recent posts"
logo = "images/icon-circle.png"
favicon = "favicon.ico"
dateFormat = "2 January 2006"
rss = true
showRelatedPosts = true

# beautiful-hugo settings
since = 2021
selfHosted = false # Search icon is not functional in self hosted mode..
mainSections = ["post"]
hideAuthor = true
socialShare = true
gcse = "ddc7e117c445f2ff2"
commit = "https://github.com/rouke-broersma/rouke-broersma.github.io/tree/"

# hugo-social-metadata settings
description = "I write short(ish) blogposts about things that interest me."
keywords = "short, blog, broersma, tech, azure, dotnet, mutation-testing, stryker"
twitterUsername = "@roukebroersma"
socialImage = "images/icon-circle.png"

# Giscus comments
giscusRepo = "rouke-broersma/rouke-broersma.github.io"
giscusRepoId = "MDEwOlJlcG9zaXRvcnkzNTQzNzgxNjg="
giscusCategory = "Comments"
giscusCategoryId = "MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyODY1Mjk4"
